es =
  signIn: "Iniciar sesión"
  signOut: "Salir"
  signUp: "Registrarse"
  OR: "O"
  forgotPassword: "¿Ha olvidado su contraseña?"
  emailAddress: "Email"
  emailResetLink: "Reiniciar Email"
  dontHaveAnAccount: "¿No tienes cuenta aún?"
  resetYourPassword: "Resetear tu contraseña"
  updateYourPassword: "Actualizar tu contraseña"
  password: "Contraseña"
  usernameOrEmail: "Usuario o email"
  email: "Email"
  ifYouAlreadyHaveAnAccount: "Ya tienes cuenta"
  signUpWithYourEmailAddress: "Regístrate con tú email"
  username: "Usuario"
  optional: "Opcional"
  signupCode: "Código para registrarse"
  clickAgree: "Si haces clic en Registrarse estás de acuerdo con la"
  privacyPolicy: "Política de Privacidad"
  terms: "Términos de Uso"
  sign: "Registrarse"
  configure: "Configurando..."
  with: "con"
  createAccount: "Crear cuenta"
  verificationPending: "Confirma tu cuenta de correo"
  verificationPendingDetails: "Un correo ha sido enviado a tu correo. Haz click en el link de confirmación para activar la cuenta."
  and: "y"

  error:
    minChar: "7 carácteres mínimo."
    pwOneLetter: "mínimo una letra."
    pwOneDigit: "mínimo un dígito."
    usernameRequired: "Usuario es necesario."
    emailRequired: "Email es necesario."
    signupCodeRequired: "Es necesario un código para Registarse."
    signupCodeIncorrect: "El código para Registrarse no coincide."
    signInRequired: "Debes iniciar sesión para hacer eso."
    usernameIsEmail: "Usuario no puede ser Email."

T9n.map "es", es
